services:
  rivian-nginx:
    image: nginx:latest
    container_name: rivian-nginx
    ports:
      - "4444:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - 'rivian-be'
      # - 'rivian-fe'

  rivian-be:
    image: nenad-jovicic/rivian-be
    container_name: rivian-be
    build:
      context: ./.docker
      dockerfile: ./app.Dockerfile
    ports:
      - '9221:9221'
    volumes:
      - ./:/home/app
    expose:
      - '3000'
    environment:
      DB_CONNECTION: postgres
      DB_HOST: rivian-db
      POSTGRES_USER: rivian
      POSTGRES_PASSWORD: rivian-password
      POSTGRES_DB: rivian
      JWT_SECRET: rivian-secret
      REFRESH_TOKEN_EXP: '90 days'
      TOKEN_EXP: '6000s' # this long only for testing purposes in Postman, so I don't have to request new token every time
      DB_PORT: 5432

  rivian-db:
    image: postgres:14
    container_name: rivian-db
    restart: always
    expose:
      - '5432'
    ports:
      - '12345:5432'
    environment:
      POSTGRES_PASSWORD: rivian-password
      POSTGRES_USER: rivian
      POSTGRES_DB: rivian
